[package]
name = "libra2-transaction-filters"
description = "The transaction filters used by various Libra2 components."
version = "0.1.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
libra2-crypto = { workspace = true }
libra2-types = { workspace = true }
move-core-types = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }

[dev-dependencies]
libra2-crypto = { workspace = true, features = ["fuzzing", "testing"] }

[features]
fuzzing = []
