[package]
name = "libra2-network-discovery"
description = "Libra2 Network Peer Discovery"
version = "0.1.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
libra2-channels = { workspace = true }
libra2-config = { workspace = true }
libra2-crypto = { workspace = true }
libra2-event-notifications = { workspace = true }
libra2-logger = { workspace = true }
libra2-metrics-core = { workspace = true }
libra2-network = { workspace = true }
libra2-rest-client = { workspace = true }
libra2-short-hex-str = { workspace = true }
libra2-time-service = { workspace = true }
libra2-types = { workspace = true }
bcs = { workspace = true }
futures = { workspace = true }
once_cell = { workspace = true }
serde_yaml = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }

[dev-dependencies]
libra2-config = { workspace = true, features = ["testing"] }
libra2-netcore = { workspace = true, features = ["fuzzing"] }
libra2-temppath = { workspace = true }
rand = { workspace = true }
