[package]
name = "basic_coin"
version = "0.0.0"

[addresses]
named_addr = "0xCAFE"

[dependencies.AptosStdlib]
git = 'https://github.com/libra2org/libra2-framework.git'
rev = 'main'
subdir = 'libra2-stdlib'
