[package]
name = "libra2-consensus-notifications"
description = "The notification interface between state sync and consensus"
version = "0.1.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
libra2-crypto = { workspace = true }
libra2-runtimes = { workspace = true }
libra2-types = { workspace = true }
async-trait = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
claims = { workspace = true }
move-core-types = { workspace = true }
