[package]
name = "libra2-vm-genesis"
description = "Libra2 vm genesis"
version = "0.1.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
libra2-cached-packages =  { workspace = true }
libra2-crypto = { workspace = true }
libra2-framework =  { workspace = true }
libra2-gas-schedule = { workspace = true } 
libra2-types = { workspace = true }
libra2-vm = { workspace = true }
libra2-vm-types = { workspace = true }
bcs = { workspace = true }
bytes = { workspace = true }
claims = { workspace = true }
move-binary-format = { workspace = true }
move-core-types = { workspace = true }
move-vm-runtime = { workspace = true }
move-vm-types = { workspace = true }
once_cell = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
libra2-proptest-helpers = { workspace = true }
move-core-types = { workspace = true }
proptest = { workspace = true }
proptest-derive = { workspace = true }

[features]
default = []
fuzzing = ["libra2-types/fuzzing", "move-core-types/fuzzing", "move-vm-types/fuzzing"]
