[package]
name = "aptos-peer-monitoring-service-server"
description = "The peer monitoring service (server-side)"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
libra2-bounded-executor = { workspace = true }
libra2-build-info = { workspace = true }
libra2-channels = { workspace = true }
libra2-config = { workspace = true }
aptos-logger = { workspace = true }
libra2-metrics-core = { workspace = true }
aptos-netcore = { workspace = true }
aptos-network = { workspace = true }
aptos-peer-monitoring-service-types = { workspace = true }
aptos-storage-interface = { workspace = true }
libra2-time-service = { workspace = true }
libra2-types = { workspace = true }
bcs = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
libra2-crypto = { workspace = true }
aptos-network = { workspace = true, features = ["fuzzing"] }
libra2-time-service = { workspace = true, features = ["testing"] }
claims = { workspace = true }
maplit = { workspace = true }
mockall = { workspace = true }
rand = { workspace = true }
