[package]
name = "aptos-storage-service-server"
description = "The Aptos storage service (server-side)"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
libra2-channels = { workspace = true }
libra2-config = { workspace = true }
libra2-infallible = { workspace = true }
aptos-logger = { workspace = true }
libra2-metrics-core = { workspace = true }
aptos-network = { workspace = true }
aptos-storage-interface = { workspace = true }
aptos-storage-service-notifications = { workspace = true }
aptos-storage-service-types = { workspace = true }
libra2-time-service = { workspace = true }
libra2-types = { workspace = true }
arc-swap = { workspace = true }
bcs = { workspace = true }
bytes = { workspace = true }
dashmap = { workspace = true }
futures = { workspace = true }
mini-moka = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
aptos-bitvec = { workspace = true }
libra2-config = { workspace = true, features = ["fuzzing"] }
libra2-crypto = { workspace = true }
aptos-netcore = { workspace = true }
aptos-storage-interface = { workspace = true }
libra2-time-service = { workspace = true, features = ["async", "testing"] }
libra2-types = { workspace = true }
claims = { workspace = true }
maplit = { workspace = true }
mockall = { workspace = true }
rand = { workspace = true }
