[package]
name = "libra2-keyless-pepper-common"
description = "Libra2 Keyless pepper library"
version = "0.1.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
libra2-crypto = { workspace = true }
libra2-crypto-derive = { workspace = true }
aptos-dkg = { workspace = true }
libra2-types = { workspace = true }
ark-bls12-381 = { workspace = true }
ark-ec = { workspace = true }
ark-ff = { workspace = true }
ark-serialize = { workspace = true }
ark-std = { workspace = true }
bcs = { workspace = true }
blstrs = { workspace = true }
derivation-path = { workspace = true }
ed25519-dalek = { workspace = true }
hex = { workspace = true }
hmac = { workspace = true }
jsonwebtoken = { workspace = true }
once_cell = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
serde = { workspace = true }
serde-big-array = { workspace = true }
sha2_0_10_6 = { workspace = true }

[package.metadata.cargo-machete]
ignored = ["bcs"]
