[package]
name = "bcs_stream"
version = "0.0.0"

[addresses]
bcs_stream = "0xCAFE"

[dependencies]
Libra2Stdlib = { git = "https://github.com/libra2org/libra2-framework.git", subdir = "libra2-stdlib", rev = "mainnet" }
