[package]
name = "aptos-keyless-pepper-example-client-rust"
description = "Aptos Keyless pepper service"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
libra2-crypto = { workspace = true }
libra2-infallible = { workspace = true }
aptos-keyless-pepper-common = { workspace = true }
libra2-types = { workspace = true }
ark-bls12-381 = { workspace = true }
ark-serialize = { workspace = true }
bcs = { workspace = true }
firestore = { workspace = true }
hex = { workspace = true }
reqwest = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
