[package]
name = "libra2-network"
description = "Libra2 networking stack"
version = "0.1.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
libra2-bitvec = { workspace = true }
libra2-channels = { workspace = true }
libra2-compression = { workspace = true }
libra2-config = { workspace = true }
libra2-crypto = { workspace = true }
libra2-id-generator = { workspace = true }
libra2-infallible = { workspace = true }
libra2-logger = { workspace = true }
libra2-memsocket = { workspace = true, optional = true }
libra2-metrics-core = { workspace = true }
libra2-netcore = { workspace = true }
libra2-num-variants = { workspace = true }
libra2-peer-monitoring-service-types = { workspace = true }
libra2-proptest-helpers = { workspace = true, optional = true }
libra2-short-hex-str = { workspace = true }
libra2-time-service = { workspace = true }
libra2-types = { workspace = true }
arc-swap = { workspace = true }
async-trait = { workspace = true }
bcs = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
futures-util = { workspace = true }
hex = { workspace = true }
itertools = { workspace = true }
maplit = { workspace = true }
once_cell = { workspace = true }
ordered-float = { workspace = true }
pin-project = { workspace = true }
proptest = { workspace = true, optional = true }
proptest-derive = { workspace = true, optional = true }
rand = { workspace = true, features = ["small_rng"] }
# Note: we cannot rely on the workspace version of rand. So we use this workaround. See:
# https://github.com/aptos-labs/aptos-core/blob/main/state-sync/libra2-data-client/Cargo.toml#L41.
# See also https://github.com/aptos-labs/aptos-core/issues/13031
rand_latest = { package = "rand", version = "0.8.5" }
serde = { workspace = true }
serde_bytes = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-retry = { workspace = true }
tokio-stream = { workspace = true }
tokio-util = { workspace = true }

[dev-dependencies]
libra2-bitvec = { workspace = true, features = ["fuzzing"] }
libra2-config = { workspace = true, features = ["testing"] }
libra2-memsocket = { workspace = true }
libra2-netcore = { workspace = true, features = ["testing"] }
libra2-proptest-helpers = { workspace = true }
libra2-time-service = { workspace = true, features = ["testing"] }
libra2-types = { workspace = true, features = ["fuzzing"] }
proptest = { workspace = true }
proptest-derive = { workspace = true }
rand_core = { workspace = true }

[features]
default = []
fuzzing = ["libra2-bitvec/fuzzing", "libra2-config/fuzzing", "libra2-crypto/fuzzing", "libra2-types/fuzzing", "libra2-proptest-helpers", "libra2-time-service/testing", "libra2-types/fuzzing", "libra2-memsocket/testing", "libra2-netcore/fuzzing", "proptest", "proptest-derive"]
testing = ["libra2-config/testing", "libra2-time-service/testing", "libra2-memsocket/testing", "libra2-netcore/testing"]

[package.metadata.cargo-machete]
ignored = ["serde_bytes"]
