[package]
name = "libra2-gas-meter"
description = "Gas meter implementation for the Libra2 blockchain"
version = "0.1.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
libra2-gas-algebra = { workspace = true }
libra2-gas-schedule = { workspace = true }
libra2-logger = { workspace = true }
libra2-types = { workspace = true }
libra2-vm-types = { workspace = true }
move-binary-format = { workspace = true }
move-core-types = { workspace = true }
move-vm-types = { workspace = true }
