[package]
name = "aptos-executor-types"
description = "Aptos executor interface types"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
libra2-crypto = { workspace = true }
libra2-drop-helper = { workspace = true }
libra2-infallible = { workspace = true }
libra2-metrics-core = { workspace = true }
aptos-scratchpad = { workspace = true }
libra2-secure-net = { workspace = true }
aptos-storage-interface = { workspace = true }
libra2-types = { workspace = true }
bcs = { workspace = true }
criterion = { workspace = true }
derive_more = { workspace = true }
itertools = { workspace = true }
once_cell = { workspace = true }
ouroboros = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
libra2-types = { workspace = true, features = ["fuzzing"] }

[features]
default = []
fuzzing = ["libra2-crypto/fuzzing", "libra2-types/fuzzing"]
bench = []

[[bench]]
name = "default"
harness = false
