[package]
name = "libra2-proptest-helpers"
description = "Libra2 proptest helpers"
version = "0.1.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
crossbeam = { workspace = true }
proptest = { workspace = true }
proptest-derive = { workspace = true }


