[package]
name = "libra2-db-tool"
version = "0.1.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
libra2-backup-cli = { workspace = true }
aptos-block-executor = { workspace = true }
libra2-config = { workspace = true }
libra2-db = { workspace = true, features = ["db-debugger"] }
libra2-db-indexer = { workspace = true }
libra2-executor = { workspace = true }
libra2-executor-types = { workspace = true }
libra2-logger = { workspace = true }
libra2-storage-interface = { workspace = true }
libra2-temppath = { workspace = true }
libra2-types = { workspace = true }
aptos-vm = { workspace = true }
bcs = { workspace = true }
clap = { workspace = true }
itertools = { workspace = true }
rayon = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
libra2-backup-cli = { workspace = true, features = ["testing"] }
libra2-backup-service = { workspace = true }
libra2-executor-test-helpers = { workspace = true }
aptos-indexer-grpc-table-info = { workspace = true }
