[package]
name = "test_package"
version = "0.0.0"
upgrade_policy = "compatible"

[dependencies]
Libra2Framework = { git = "https://github.com/libra2org/libra2-framework.git", subdir = "libra2-framework", rev = "mainnet" }

[addresses]
# change it to `source_addr = "_" when calling `create-resource-account-and-publish-package` from the cli
source_addr = "0xcafe"
