[package]
name = "Marketplace"
version = "0.0.0"

[addresses]
marketplace = "_"

[dependencies]
Libra2Framework = { git = "https://github.com/libra2org/libra2-framework.git", subdir = "libra2-framework", rev = "mainnet" }
Libra2Token = { git = "https://github.com/libra2org/libra2-framework.git", subdir = "libra2-token", rev = "mainnet" }
Libra2TokenObjects = { git = "https://github.com/libra2org/libra2-framework.git", subdir = "libra2-token-objects", rev = "mainnet" }