[package]
name = "ApiTest"
version = "0.0.0"

[addresses]
# test user address to be installed dynamically on build

[dependencies]
Libra2Framework = { local = "../../libra2-move/framework/libra2-framework" }
