[package]
name = "libra2-netcore"
description = "Libra2 netcore"
version = "0.1.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
libra2-memsocket = { workspace = true }
aptos-proxy = { workspace = true }
libra2-types = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
pin-project = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
url = { workspace = true }

[dev-dependencies]
libra2-memsocket = { workspace = true }
libra2-types = { workspace = true, features = ["fuzzing"] }

[features]
default = []
fuzzing = ["libra2-memsocket/fuzzing", "libra2-types/fuzzing"]
testing = ["libra2-memsocket/testing"]
