[package]
name = "libra2-vm-benchmarks"
version = "0.1.1"
edition = "2021"
license = { workspace = true }

[dependencies]
libra2-cached-packages = { workspace = true }
libra2-framework = { workspace = true }
libra2-language-e2e-tests = { workspace = true }
libra2-types = { workspace = true }
bcs = { workspace = true }
clap = { workspace = true }
move-binary-format = { workspace = true }
move-core-types = { workspace = true }
