[package]
name = "libra2-release-builder"
description = "Tooling for building the governance proposal script used for the network"
version = "0.1.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
libra2 = { workspace = true, features = [ "no-upload-proposal" ] }
libra2-build-info = { workspace = true }
libra2-crypto = { workspace = true }
libra2-framework = { workspace = true }
libra2-gas-profiling = { workspace = true }
libra2-gas-schedule = { workspace = true }
libra2-gas-schedule-updator = { workspace = true }
libra2-genesis = { workspace = true }
libra2-infallible = { workspace = true }
libra2-keygen = { workspace = true }
libra2-language-e2e-tests = { workspace = true }
libra2-move-debugger = { workspace = true }
libra2-rest-client = { workspace = true }
libra2-temppath = { workspace = true }
libra2-transaction-simulation = { workspace = true }
libra2-types = { workspace = true }
libra2-vm = { workspace = true }
libra2-vm-environment = { workspace = true }
libra2-vm-logging = { workspace = true }
libra2-vm-types = { workspace = true }
bcs = { workspace = true }
clap = { workspace = true }
futures = { workspace = true }
git2 = { workspace = true }
handlebars = { workspace = true }
hex = { workspace = true }
move-binary-format = { workspace = true }
move-bytecode-verifier = { workspace = true }
move-core-types = { workspace = true }
move-model = { workspace = true }
move-vm-runtime = { workspace = true }
move-vm-types = { workspace = true }
once_cell = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
sha3 = { workspace = true }
strum = { workspace = true }
strum_macros = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }
walkdir = { workspace = true }

[[bin]]
name = "libra2-release-builder"
path = "src/main.rs"
