[package]
name = "libra2-indexer-transaction-generator"
description = "Indexer integration testing framework."
version = "1.0.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
# used for localnode.
libra2 = { workspace = true }
libra2-config = { workspace = true }
libra2-faucet-core = { workspace = true }
libra2-indexer-grpc-utils = { workspace = true }
libra2-protos ={ workspace = true }
clap = { workspace = true }
futures = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
tonic = { workspace = true }
url = { workspace = true }

[dev-dependencies]
itertools = { workspace = true }
tempfile = { workspace = true }
tokio-stream = { workspace = true }
