[package]
name = "aggregator_examples"
version = "0.0.0"

[addresses]
aggregator_examples = "0xCAFE"

[dependencies]
Libra2Stdlib = { git = "https://github.com/libra2org/libra2-framework.git", subdir = "libra2-stdlib", rev = "mainnet" }
Libra2Framework = { git = "https://github.com/libra2org/libra2-framework.git", subdir = "libra2-framework", rev = "mainnet" }
