# :!:>manifest
[package]
name = 'UpgradeAndGovern'
version = '1.1.0'

[addresses]
upgrade_and_govern = '_'

[dependencies.Libra2Framework]
git = "https://github.com/libra2org/libra2-framework.git"
subdir = "libra2-framework"
rev = "mainnet"