[tool.poetry]
name = "aptos-cli-e2e-tests"
package-mode = false
version = "0.1.0"
description = "Libra2 CLI E2E tests"
authors = ["Libra2 Team <info@libra2.org>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = ">=3.8.1,<=4"
libra2-sdk = "^0.10.0"
requests = "^2.31.0"

[tool.poetry.dev-dependencies]
black = "^22.6.0"
isort = "^5.10.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
