# This is a template config.yaml for a parquet processor
health_check_port: 8085
server_config:
  processor_config:
    type: parquet_transaction_metadata_processor
    channel_size: 100
    max_buffer_size: 100000000 # 300MB to keep the number of files low in GCS.
    upload_interval: 30 # if buffer hasn't reached 300MB within 30 mins, we upload the buffer to GCS
  transaction_stream_config:
    indexer_grpc_data_service_address: "https://grpc.mainnet.aptoslabs.com:443"
    auth_token: "AUTH_TOKEN"
    request_name_header: "parquet_transaction_metadata_processor"
  processor_mode:
    type: "default"
    initial_starting_version: 0
  db_config:
    type: parquet_config
    connection_string: postgresql://postgres:@localhost:5432/example
    bucket_name: "aptos-indexer-data-etl-yuunnet"
    bucket_root: "new-repo-migration"