[package]
name = "ManagedFungibleToken"
version = "0.0.0"

[addresses]
libra2_framework = "0x1"
libra2_token_objects = "0x4"
example_addr = "_"

[dependencies]
Libra2Framework = { git = "https://github.com/libra2org/libra2-framework.git", subdir = "libra2-framework", rev = "mainnet" }
Libra2TokenObjects = { git = "https://github.com/libra2org/libra2-framework.git", subdir = "libra2-token-objects", rev = "mainnet" }
ManagedFungibleAsset = { local = "../managed_fungible_asset" }
