[package]
name = "libra2-db"
description = "Libra2 database"
version = "0.1.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
libra2-accumulator = { workspace = true }
libra2-config = { workspace = true }
libra2-crypto = { workspace = true }
libra2-db-indexer = { workspace = true }
libra2-db-indexer-schemas = { workspace = true, features = ["fuzzing"] }
libra2-executor-types = { workspace = true }
libra2-experimental-runtimes = { workspace = true }
libra2-infallible = { workspace = true }
libra2-jellyfish-merkle = { workspace = true }
libra2-logger = { workspace = true }
libra2-metrics-core = { workspace = true }
libra2-proptest-helpers = { workspace = true, optional = true }
aptos-resource-viewer = { workspace = true }
libra2-rocksdb-options = { workspace = true }
libra2-schemadb = { workspace = true }
libra2-scratchpad = { workspace = true }
libra2-storage-interface = { workspace = true, features = ["fuzzing"] }
libra2-temppath = { workspace = true, optional = true }
libra2-types = { workspace = true }
arc-swap = { workspace = true }
arr_macro = { workspace = true }
bcs = { workspace = true }
byteorder = { workspace = true }
claims = { workspace = true }
clap = { workspace = true, optional = true }
crossbeam-channel = { workspace = true, optional = true }
dashmap = { workspace = true }
either = { workspace = true }
hex = { workspace = true }
indicatif = { workspace = true, optional = true }
itertools = { workspace = true }
lru = { workspace = true }
move-core-types = { workspace = true }
once_cell = { workspace = true }
owo-colors = { workspace = true, optional = true }
proptest = { workspace = true, optional = true }
proptest-derive = { workspace = true, optional = true }
rayon = { workspace = true }
serde = { workspace = true }
static_assertions = { workspace = true }
status-line = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
aptos-block-executor = { workspace = true }
libra2-executor-types = { workspace = true }
libra2-jellyfish-merkle = { workspace = true, features = ["fuzzing"] }
libra2-proptest-helpers = { workspace = true }
libra2-schemadb = { workspace = true, features = ["fuzzing"] }
libra2-scratchpad = { workspace = true, features = ["fuzzing"] }
libra2-temppath = { workspace = true }
libra2-types = { workspace = true }
ouroboros = { workspace = true }
proptest = { workspace = true }
proptest-derive = { workspace = true }
rand = { workspace = true }

[features]
default = []
fuzzing = ["proptest", "proptest-derive", "libra2-proptest-helpers", "libra2-temppath", "libra2-crypto/fuzzing", "libra2-jellyfish-merkle/fuzzing", "libra2-types/fuzzing", "libra2-executor-types/fuzzing", "libra2-schemadb/fuzzing", "libra2-scratchpad/fuzzing"]
consensus-only-perf-test = []
db-debugger = ["libra2-temppath", "clap", "crossbeam-channel", "owo-colors", "indicatif"]
