[package]
name = "aptos-executor-benchmark"
description = "Aptos executor benchmark"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
aptos-aggregator = { workspace = true }
aptos-block-executor = { workspace = true }
aptos-block-partitioner = { workspace = true }
libra2-config = { workspace = true }
libra2-crypto = { workspace = true }
aptos-db = { workspace = true }
aptos-executor = { workspace = true }
aptos-executor-service = { workspace = true }
aptos-executor-types = { workspace = true }
aptos-experimental-ptx-executor = { workspace = true }
aptos-experimental-runtimes = { workspace = true }
aptos-genesis = { workspace = true, features = ["testing"] }
libra2-infallible = { workspace = true }
aptos-jellyfish-merkle = { workspace = true }
libra2-logger = { workspace = true }
libra2-metrics-core = { workspace = true }
aptos-mvhashmap = { workspace = true }
aptos-node-resource-metrics = { workspace = true }
libra2-push-metrics =  { workspace = true }
libra2-sdk = { workspace = true }
aptos-storage-interface = { workspace = true }
aptos-transaction-generator-lib = { workspace = true }
aptos-transaction-workloads-lib = { workspace = true }
libra2-types = { workspace = true }
aptos-vm = { workspace = true }
aptos-vm-environment = { workspace = true }
aptos-vm-logging = { workspace = true }
aptos-vm-types = { workspace = true }
async-trait = { workspace = true }
bcs = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true }
dashmap = { workspace = true }
derivative = { workspace = true }
indicatif = { workspace = true }
itertools = { workspace = true }
move-core-types = { workspace = true }
move-vm-types = { workspace = true }
num_cpus = { workspace = true }
once_cell = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
thread_local = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }

[target.'cfg(unix)'.dependencies]
libra2-profiler = { workspace = true }
jemallocator = { version = "0.5.0", features = [
    "profiling",
    "unprefixed_malloc_on_supported_platforms",
] }

[dev-dependencies]
libra2-temppath = { workspace = true }

[features]
default = []
fuzzing = ["libra2-config/fuzzing", "libra2-crypto/fuzzing", "libra2-types/fuzzing"]
