[package]
name = "aptos-event-notifications"
description = "The notification service offered by state sync for on-chain events"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
libra2-channels = { workspace = true }
libra2-id-generator = { workspace = true }
libra2-infallible = { workspace = true }
aptos-storage-interface = { workspace = true }
libra2-types = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
libra2-crypto = { workspace = true }
aptos-db = { workspace = true }
aptos-executor-test-helpers = { workspace = true }
libra2-temppath = { workspace = true }
aptos-vm = { workspace = true }
aptos-vm-genesis = { workspace = true }
bcs = { workspace = true }
claims = { workspace = true }
move-binary-format = { workspace = true }
move-core-types = { workspace = true }
