[package]
name = "libra2-rosetta-cli"
description = "Libra2 Rosetta CLI for testing"
version = "0.0.2"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
libra2 = { workspace = true }
libra2-logger = { workspace = true }
libra2-rosetta = { workspace = true }
libra2-types = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }

