[package]
name = "calculator"
version = "0.0.0"

[addresses]
account = "_"

[dependencies]
Libra2Framework = { local = "../../../framework/libra2-framework" }
AptosStdlib = { local = "../../../framework/libra2-stdlib" }
