[package]
name = "aptos-testcases"
description = "Aptos compatibility tests"
version = "0.0.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
aptos = { workspace = true, features = ["fuzzing"] }
libra2-config = { workspace = true }
aptos-forge = { workspace = true }
libra2-global-constants = { workspace = true }
libra2-keygen = { workspace = true }
libra2-logger = { workspace = true }
aptos-release-builder = { workspace = true }
libra2-rest-client = { workspace = true }
libra2-runtimes = { workspace = true }
libra2-sdk = { workspace = true }
libra2-temppath = { workspace = true }
libra2-types = { workspace = true }
async-trait = { workspace = true }
bcs = { workspace = true }
csv = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
itertools = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
assert_approx_eq = { workspace = true }

[[test]]
name = "forge-local-compatibility"
harness = false

[[test]]
name = "forge-local-performance"
harness = false
