[package]
name = "libra2-executor-test-helpers"
description = "Libra2 executor test helpers"
version = "0.1.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
libra2-cached-packages = { workspace = true }
libra2-config = { workspace = true }
libra2-consensus-types = { workspace = true }
libra2-crypto = { workspace = true }
libra2-db = { workspace = true, features = ["fuzzing"] }
libra2-executor = { workspace = true }
libra2-executor-types = { workspace = true }
libra2-sdk = { workspace = true }
libra2-storage-interface = { workspace = true }
libra2-temppath = { workspace = true }
libra2-types = { workspace = true }
libra2-vm = { workspace = true }
libra2-vm-genesis = { workspace = true }
move-core-types = { workspace = true, features = ["fuzzing"] }
rand = { workspace = true }
