[package]
name = "hello_prover"
version = "0.0.0"

[dependencies]
Libra2Framework = { git = "https://github.com/libra2org/libra2-framework.git", subdir = "libra2-framework/", rev = "main" }

[addresses]


