[package]
name = "DrandLottery"
version = "0.0.1"

[dependencies]
Libra2Framework = { git = "https://github.com/libra2org/libra2-framework.git", subdir = "libra2-framework", rev = "mainnet" }
#Libra2Stdlib = { git = "https://github.com/libra2org/libra2-framework.git", subdir = "libra2-stdlib", rev = "mainnet" }


[addresses]
std = "0x1"
libra2_std = "0x1"
libra2_framework = "0x1"
drand = "_"
