[package]
name = "dispatching"
version = "0.0.0"


[addresses]
dispatching = "_"

#[dev-addresses]
#dispatching = "0xd119"

[dependencies]
Libra2Framework = { local = "../../framework/libra2-framework" }
