[package]
name = "libra2-db-indexer"
description = "Libra2DB Internal Indexer"
version = "0.1.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
libra2-config = { workspace = true }
libra2-db-indexer-schemas = { workspace = true }
libra2-logger = { workspace = true }
libra2-metrics-core = { workspace = true }
libra2-resource-viewer = { workspace = true }
libra2-rocksdb-options = { workspace = true }
libra2-schemadb = { workspace = true }
libra2-storage-interface = { workspace = true }
libra2-types = { workspace = true }
bcs = { workspace = true }
bytes = { workspace = true }
dashmap = { workspace = true }
move-core-types = { workspace = true }
once_cell = { workspace = true }

[dev-dependencies]
libra2-proptest-helpers = { workspace = true }
libra2-schemadb = { workspace = true, features = ["fuzzing"] }
libra2-types = { workspace = true, features = ["fuzzing"] }
rand = { workspace = true }

[features]
default = []
fuzzing = ["libra2-types/fuzzing", "libra2-schemadb/fuzzing"]
