[package]
name = "smoke-test"
description = "Aptos end to end tests"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
aptos = { workspace = true, features = ["fuzzing"] }
libra2-api-types = { workspace = true }
libra2-bitvec = { path = "../../crates/libra2-bitvec" }
aptos-cached-packages = { workspace = true }
libra2-config = { workspace = true, features = ["smoke-test"] }
libra2-consensus = { workspace = true }
libra2-crypto = { workspace = true }
aptos-db = { workspace = true }
aptos-db-indexer-schemas = { workspace = true }
libra2-dkg = { workspace = true }
libra2-faucet-core = { workspace = true }
aptos-forge = { workspace = true }
aptos-framework = { workspace = true }
aptos-gas-algebra = { workspace = true }
aptos-gas-schedule = { workspace = true, features = ["testing"] }
libra2-global-constants = { workspace = true }
aptos-indexer = { workspace = true }
aptos-indexer-grpc-table-info = { workspace = true }
libra2-inspection-service = { workspace = true }
libra2-keygen = { workspace = true }
libra2-move-debugger = { workspace = true }
aptos-release-builder = { workspace = true }
libra2-rest-client = { workspace = true }
libra2-rosetta = { workspace = true }
aptos-schemadb = { workspace = true }
libra2-sdk = { workspace = true }
aptos-storage-interface = { workspace = true }
libra2-temppath = { workspace = true }
libra2-transaction-filters = { workspace = true }
libra2-types = { workspace = true }
aptos-vm = { workspace = true }
bcs = { workspace = true }
diesel = { workspace = true, features = [
    "chrono",
    "postgres",
    "r2d2",
    "numeric",
    "serde_json",
] }
digest = { workspace = true }
ethers = { workspace = true }
hex = { workspace = true }
hyper = { workspace = true }
move-binary-format = { workspace = true }
move-core-types = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
url = { workspace = true }
walkdir = { workspace = true }

[dev-dependencies]
aptos-backup-cli = { workspace = true }
aptos-db-indexer = { workspace = true, features = ["fuzzing"] }
libra2-genesis = { workspace = true }
libra2-infallible = { workspace = true }
libra2-logger = { workspace = true }
libra2-secure-storage = { workspace = true }
libra2-time-service = { workspace = true }
libra2-vault-client = { workspace = true }
base64 = { workspace = true }
futures = { workspace = true }
itertools = { workspace = true }
num_cpus = { workspace = true }
once_cell = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
serde_yaml = { workspace = true }
tempfile = { workspace = true }
