[package]
name = "aptos-peer-monitoring-service-client"
description = "The Aptos peer monitoring service (client-side)"
version = "0.1.0"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
libra2-channels = { workspace = true }
libra2-config = { workspace = true }
libra2-id-generator = { workspace = true }
libra2-infallible = { workspace = true }
aptos-logger = { workspace = true }
libra2-metrics-core = { workspace = true }
aptos-network = { workspace = true }
aptos-peer-monitoring-service-types = { workspace = true }
libra2-time-service = { workspace = true }
libra2-types = { workspace = true }
enum_dispatch = { workspace = true }
futures = { workspace = true }
once_cell = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
libra2-build-info = { workspace = true }
libra2-config = { workspace = true }
aptos-netcore = { workspace = true }
aptos-network = { workspace = true, features = ["fuzzing"] }
aptos-peer-monitoring-service-server = { workspace = true }
bcs = { workspace = true }
maplit = { workspace = true }
tokio-stream = { workspace = true }
