[package]
name = "libra2-executor"
description = "Libra2 executor"
version = "0.1.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
aptos-block-executor = { workspace = true }
libra2-consensus-types = { workspace = true }
libra2-crypto = { workspace = true }
libra2-drop-helper = { workspace = true }
libra2-executor-service = { workspace = true }
libra2-executor-types = { workspace = true }
libra2-experimental-runtimes = { workspace = true }
aptos-indexer-grpc-table-info = { workspace = true }
libra2-infallible = { workspace = true }
libra2-logger = { workspace = true }
libra2-metrics-core = { workspace = true }
libra2-sdk = { workspace = true }
libra2-storage-interface = { workspace = true }
libra2-types = { workspace = true }
aptos-vm = { workspace = true }
bcs = { workspace = true }
bytes = { workspace = true }
fail = { workspace = true }
itertools = { workspace = true }
move-core-types = { workspace = true }
once_cell = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
aptos-cached-packages = { workspace = true }
libra2-config = { workspace = true }
libra2-db = { workspace = true }
libra2-db-indexer = { workspace = true, features = ["fuzzing"] }
libra2-executor-test-helpers = { workspace = true }
libra2-storage-interface = { workspace = true }
libra2-temppath = { workspace = true }
aptos-transaction-simulation = { workspace = true }
libra2-types = { workspace = true, features = ["testing"] }
aptos-vm-genesis = { workspace = true }
arr_macro = { workspace = true }
criterion = { workspace = true }
proptest = { workspace = true }
rand = { workspace = true }

[features]
default = []
fuzzing = ["libra2-consensus-types/fuzzing", "libra2-crypto/fuzzing", "libra2-types/fuzzing", "libra2-storage-interface/fuzzing"]
failpoints = ["fail/failpoints", "aptos-vm/failpoints"]
consensus-only-perf-test = []

[[bench]]
name = "data_collection"
harness = false
