[package]
name = "libra2-txnstream-server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "signal"] }
tokio-stream = { workspace = true }
futures = { workspace = true }
tonic = { workspace = true }
tonic-health = "0.12"
prost = { workspace = true }
bcs = "0.1"

# Use the generated protos from your existing 'protos/rust' crate
libra2-protos = { workspace = true }

# Pull config / telemetry / storage from your workspace
libra2-config = { workspace = true }
libra2-telemetry = { workspace = true }
# Adjust to your actual storage crate(s)
libra2-db = { workspace = true, optional = true }

[features]
default = []