[package]
name = "libra2"
description = "Libra2 tool for management of nodes and interacting with the blockchain"
version = "7.7.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
libra2-api-types = { workspace = true }
libra2-backup-cli = { workspace = true }
libra2-bitvec = { workspace = true }
libra2-build-info = { workspace = true }
aptos-cached-packages = { workspace = true }
libra2-cli-common = { workspace = true }
# libra2-cli-common = { workspace = true }
libra2-config = { workspace = true }
libra2-crypto = { workspace = true }
libra2-faucet-core = { workspace = true }
aptos-framework = { workspace = true }
aptos-gas-profiling = { workspace = true }
aptos-gas-schedule = { workspace = true }
libra2-genesis = { workspace = true }
libra2-github-client = { workspace = true }
libra2-global-constants = { workspace = true }
aptos-indexer-grpc-server-framework = { workspace = true }
aptos-indexer-processor-sdk = { workspace = true }
libra2-keygen = { workspace = true }
libra2-ledger = { workspace = true }
libra2-localnet = { workspace = true }
libra2-logger = { workspace = true }
libra2-move-debugger = { workspace = true }
libra2-network-checker = { workspace = true }
libra2-node = { workspace = true }
aptos-node = { workspace = true }
libra2-rest-client = { workspace = true }
libra2-sdk = { workspace = true }
libra2-storage-interface = { workspace = true }
libra2-telemetry = { workspace = true }
libra2-temppath = { workspace = true }
libra2-types = { workspace = true }
aptos-vm = { workspace = true, features = ["testing"] }
aptos-vm-environment = { workspace = true }
aptos-vm-genesis = { workspace = true }
aptos-vm-logging = { workspace = true }
aptos-vm-types = { workspace = true }
aptos-workspace-server = { workspace = true }
async-trait = { workspace = true }
backoff = { workspace = true }
base64 = { workspace = true }
bcs = { workspace = true }
bollard = { workspace = true }
chrono = { workspace = true }
clap = { workspace = true, features = ["env", "unstable-styles", "wrap_help"] }
clap_complete = { workspace = true }
colored = { workspace = true }
dashmap = { workspace = true }
diesel = { workspace = true, features = ["postgres_backend"] }
diesel-async = { workspace = true }
dirs = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
indoc = { workspace = true }
itertools = { workspace = true }
legacy-move-compiler = { workspace = true }
maplit = { workspace = true }
move-binary-format = { workspace = true }
move-bytecode-source-map = { workspace = true }
move-cli = { workspace = true }
move-command-line-common = { workspace = true }
move-compiler-v2 = { workspace = true }
move-core-types = { workspace = true }
move-coverage = { workspace = true }
move-disassembler = { workspace = true }
move-ir-types = { workspace = true }
move-linter = { workspace = true }
move-model = { workspace = true }
move-package = { workspace = true }
move-prover-boogie-backend = { workspace = true }
move-symbol-pool = { workspace = true }
move-unit-test = { workspace = true, features = ["debugging"] }
move-vm-runtime = { workspace = true, features = ["testing"] }
open = { workspace = true }
pathsearch = { workspace = true }
poem = { workspace = true }
processor = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
reqwest = { workspace = true }
self_update = { git = "https://github.com/banool/self_update.git", rev = "8306158ad0fd5b9d4766a3c6bf967e7ef0ea5c4b", features = [
    "archive-zip",
    "compression-zip-deflate",
] }
serde = { workspace = true }
serde_json = { workspace = true }
serde_yaml = { workspace = true }
set_env = { workspace = true }
tempfile = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
toml = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
url = { workspace = true }

[target.'cfg(unix)'.dependencies]
jemallocator = { version = "0.5.0", features = [
    "profiling",
    "unprefixed_malloc_on_supported_platforms",
] }

[features]
default = []
fuzzing = []
no-upload-proposal = []
indexer = ["libra2-node/indexer"]
cli-framework-test-move = []

[build-dependencies]
shadow-rs = { workspace = true }
