[package]
name = "Examples"
version = "1.0.0"

[addresses]
rewards_pool = "_"

[dependencies]
Libra2Framework = { git = "https://github.com/libra2org/libra2-framework.git", subdir = "libra2-framework", rev = "mainnet" }
