[package]
name = "libra2-language-e2e-tests"
description = "Move language e2e testing framework"
version = "0.1.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
libra2-abstract-gas-usage = { workspace = true }
libra2-bitvec = { workspace = true }
libra2-block-executor = { workspace = true }
libra2-cached-packages ={ workspace = true }
libra2-crypto = { workspace = true, features = ["fuzzing"] }
libra2-framework = { workspace = true }
libra2-gas-algebra = { workspace = true }
libra2-gas-meter = { workspace = true }
libra2-gas-profiling = { workspace = true }
libra2-gas-schedule = { workspace = true }
libra2-keygen = { workspace = true }
libra2-proptest-helpers = { workspace = true }
libra2-rest-client = { workspace = true }
libra2-temppath = { workspace = true }
libra2-transaction-simulation = { workspace = true }
libra2-types = { workspace = true }
libra2-validator-interface = { workspace = true }
libra2-vm = { workspace = true }
libra2-vm-environment = { workspace = true }
libra2-vm-genesis = { workspace = true }
libra2-vm-logging = { workspace = true }
libra2-vm-types = { workspace = true }
bcs = { workspace = true }
bytes = { workspace = true }
goldenfile = { workspace = true }
move-binary-format = { workspace = true }
move-command-line-common = { workspace = true }
move-core-types = { workspace = true, features = ["fuzzing"] }
move-ir-compiler = { workspace = true }
move-model = { workspace = true }
move-vm-runtime = { workspace = true }
move-vm-types = { workspace = true }
num_cpus = { workspace = true }
once_cell = { workspace = true }
petgraph = "0.5.1"
proptest = { workspace = true }
proptest-derive = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }

[features]
default = []
fuzzing = []
