[package]
name = 'ambassador_token'
version = '1.0.0'

# do not change to "_", concrete address needed for module-publish testing framework
[addresses]
ambassador = "0xCAFE"

[dependencies]
Libra2Framework = { git = "https://github.com/libra2org/libra2-framework.git", subdir = "libra2-framework", rev = "mainnet" }
Libra2TokenObjects = { git = "https://github.com/libra2org/libra2-framework.git", subdir = "libra2-token-objects", rev = "mainnet" }
