[package]
name = "libra2-network-checker"
description = "Libra2 network checker"
version = "0.0.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
libra2-config = { workspace = true }
libra2-crypto = { workspace = true }
libra2-logger = { workspace = true }
libra2-network = { workspace = true }
libra2-types = { workspace = true }
clap = { workspace = true }
futures = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }

