[package]
name = "libra2-backup-service"
description = "Backup service"
version = "0.1.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
libra2-crypto = { workspace = true }
libra2-db = { workspace = true }
libra2-logger = { workspace = true }
libra2-metrics-core = { workspace = true }
libra2-runtimes = { workspace = true }
libra2-storage-interface = { workspace = true }
libra2-types = { workspace = true }
bcs = { workspace = true }
bytes = { workspace = true }
hyper = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
warp = { workspace = true }

[dev-dependencies]
libra2-config = { workspace = true }
libra2-db = { workspace = true, features = ["fuzzing"] }
libra2-temppath = { workspace = true }
reqwest = { workspace = true }

[features]
fuzzing = ["libra2-db/fuzzing"]
