[package]
name = "libra2-txnstream-server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread", "macros", "signal"] }
tokio-stream = { workspace = true }
futures = { workspace = true }
tonic = { workspace = true }
tonic-health = { workspace = true }
prost = { workspace = true }
bcs = { workspace = true }

# Use the generated protos from your existing 'protos/rust' crate
libra2-protos = { workspace = true }

# Pull config / telemetry / storage from your workspace
libra2-config = { workspace = true }
libra2-telemetry = { workspace = true }
# Adjust to your actual storage crate(s)
libra2-db = { workspace = true, optional = true }
clap = { version = "4.5.43", features = ["derive"] }

[features]
default = []
bin = []

[[bin]]
name = "txnstream-server"
path = "src/lib.rs"
required-features = ["bin"]