[package]
name = "libra2-vm"
description = "Libra2 VM runtime"
version = "0.1.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
libra2-aggregator = { workspace = true }
libra2-block-executor = { workspace = true }
libra2-block-partitioner = { workspace = true }
libra2-crypto = { workspace = true }
libra2-crypto-derive = { workspace = true }
libra2-experimental-runtimes = { workspace = true }
libra2-framework =  { workspace = true }
libra2-gas-algebra = { workspace = true }
libra2-gas-meter = { workspace = true }
libra2-gas-schedule = { workspace = true }
libra2-infallible = { workspace = true }
libra2-logger = { workspace = true }
libra2-memory-usage-tracker = { workspace = true }
libra2-metrics-core = { workspace = true }
libra2-mvhashmap = { workspace = true }
libra2-native-interface = { workspace = true }
libra2-table-natives = { workspace = true }
libra2-types = { workspace = true }
libra2-vm-environment = { workspace = true }
libra2-vm-logging = { workspace = true }
libra2-vm-types = { workspace = true }
ark-bn254 = { workspace = true }
ark-groth16 = { workspace = true }
bcs = { workspace = true }
bytes = { workspace = true }
claims = { workspace = true }
crossbeam-channel = { workspace = true }
derive_more = { workspace = true }
fail = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
itertools = { workspace = true }
move-binary-format = { workspace = true }
move-core-types = { workspace = true }
move-unit-test = { workspace = true, optional = true }
move-vm-metrics = { workspace = true }
move-vm-runtime = { workspace = true }
move-vm-types = { workspace = true }
num_cpus = { workspace = true }
once_cell = { workspace = true }
ouroboros = { workspace = true }
rand = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
libra2-aggregator = { workspace = true, features = ["testing"] }
libra2-block-executor = { workspace = true, features = ["testing"] }
libra2-keygen = { workspace = true }
libra2-language-e2e-tests = { workspace = true }
libra2-transaction-simulation = { workspace = true }
libra2-types = { workspace = true, features = ["fuzzing", "testing"] }
claims = { workspace = true }
move-vm-types = { workspace = true, features = ["testing"] }
proptest = { workspace = true }
rand_core = { workspace = true }
test-case = { workspace = true }

[features]
default = []
fuzzing = ["move-core-types/fuzzing", "move-binary-format/fuzzing", "move-vm-types/fuzzing", "libra2-framework/fuzzing", "libra2-types/fuzzing"]
failpoints = ["fail/failpoints", "move-vm-runtime/failpoints"]
testing = ["move-unit-test", "libra2-framework/testing"]
