[package]
name = 'tic-tac-toe'
version = '1.0.0'

[addresses]
tic_tac_toe = "_"

[dependencies]
Libra2Framework = { git = "https://github.com/libra2org/libra2-framework.git", subdir = "libra2-framework", rev = "mainnet" }
