[package]
name = "libra2-abstract-gas-usage"
version = "0.1.1"
edition = "2021"
license = { workspace = true }

[dependencies]
anyhow = { workspace = true }
libra2-gas-algebra = { workspace = true }
libra2-gas-meter = { workspace = true }
libra2-gas-schedule = { workspace = true }
libra2-vm-types = { workspace = true }
move-binary-format = { workspace = true }
