[package]
name = "libra2-storage-service-types"
description = "Common types offered by the Libra2 storage service"
version = "0.1.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
aptos-compression = { workspace = true }
libra2-config = { workspace = true }
libra2-crypto = { workspace = true }
libra2-time-service = { workspace = true }
libra2-types = { workspace = true }
bcs = { workspace = true }
num-traits = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
libra2-time-service = { workspace = true, features = ["testing"] }
claims = { workspace = true }
proptest = { workspace = true }
rand = { workspace = true }
