[package]
name = "libra2-experimental-layered-map"
description = "Libra2 LayeredMap"
version = "0.1.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
ahash = { workspace = true }
libra2-crypto = { workspace = true }
libra2-drop-helper = { workspace = true }
libra2-infallible = { workspace = true }
libra2-metrics-core = { workspace = true }
bitvec = "1.0.1"
itertools = { workspace = true }
once_cell = { workspace = true }

[dev-dependencies]
anyhow = { workspace = true }
libra2-schemadb = { workspace = true }
libra2-temppath = { workspace = true }
criterion = { workspace = true }
itertools = { workspace = true }
proptest = { workspace = true }
rand = { workspace = true }
rocksdb = { workspace = true }

[target.'cfg(unix)'.dependencies]
jemallocator = { version = "0.5.0", features = [
    "profiling",
    "unprefixed_malloc_on_supported_platforms",
] }

[lib]
bench = false

[[bench]]
name = "sorting"
harness = false

[[bench]]
name = "maps"
harness = false
