[package]
name = "libra2-indexer-grpc-fullnode"
description = "Libra2 Indexer GRPC runtime on fullnode."
version = "1.0.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
bcs = { workspace = true }
bytes = { workspace = true }
chrono = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
hyper = { workspace = true }
itertools = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tonic = { workspace = true }
tonic-reflection = { workspace = true }

libra2-api = { workspace = true }
libra2-api-types = { workspace = true }
libra2-bitvec = { workspace = true }
libra2-config = { workspace = true }
libra2-indexer-grpc-utils = { workspace = true }
libra2-logger = { workspace = true }
libra2-mempool = { workspace = true }
libra2-metrics-core = { workspace = true }
libra2-moving-average = { workspace = true }
libra2-protos = { workspace = true }
libra2-runtimes = { workspace = true }
libra2-storage-interface = { workspace = true }
libra2-types = { workspace = true }

move-core-types = { workspace = true }

[dev-dependencies]
goldenfile = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }

libra2-api-test-context = { workspace = true }
libra2-crypto = { workspace = true }
libra2-db = { workspace = true }
libra2-executor = { workspace = true }
libra2-executor-types = { workspace = true }
libra2-framework = { workspace = true }
libra2-genesis = { workspace = true }
libra2-global-constants = { workspace = true }
libra2-mempool = { workspace = true }
libra2-mempool-notifications = { workspace = true }
libra2-proptest-helpers = { workspace = true }
libra2-sdk = { workspace = true }
libra2-secure-storage = { workspace = true }
libra2-temppath = { workspace = true }
libra2-vm = { workspace = true }
libra2-vm-validator = { workspace = true }
