[package]
name = "stablecoin"
version = "0.0.0"


[addresses]
stablecoin = "_"
master_minter = "_"
minter = "_"
pauser = "_"
denylister = "_"

[dev-addresses]
stablecoin = "0xcafe"
master_minter = "0xbab"
minter = "0xface"
pauser = "0xdafe"
denylister = "0xcade"

[dependencies]
Libra2Framework = { git = "https://github.com/libra2org/libra2-framework.git", subdir = "libra2-framework", rev = "mainnet" }
