[package]
name = "libra2-executor-service"
description = "Libra2 executor service"
version = "0.1.1"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
aptos-block-executor = { workspace = true }
libra2-block-partitioner = { workspace = true }
libra2-config = { workspace = true }
libra2-infallible = { workspace = true }
libra2-keygen = { workspace = true }
aptos-language-e2e-tests = { workspace = true }
libra2-logger = { workspace = true }
libra2-metrics-core = { workspace = true }
libra2-node-resource-metrics = { workspace = true }
libra2-push-metrics =  { workspace = true }
libra2-secure-net = { workspace = true }
libra2-storage-interface = { workspace = true }
aptos-transaction-simulation = { workspace = true }
libra2-types = { workspace = true }
aptos-vm = { workspace = true }
bcs = { workspace = true }
clap = { workspace = true }
crossbeam-channel = { workspace = true }
ctrlc = "3.4.0"
dashmap = { workspace = true }
itertools = { workspace = true }
num_cpus = { workspace = true }
once_cell = { workspace = true }
rayon = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
aptos-language-e2e-tests = { workspace = true }
aptos-vm = { workspace = true }
