[package]
name = "Examples"
version = "0.0.0"

[dependencies]
Libra2Framework = { git = "https://github.com/libra2org/libra2-framework.git", subdir = "libra2-framework", rev = "mainnet" }
Libra2Token = { git = "https://github.com/libra2org/libra2-framework.git", subdir = "libra2-token", rev = "mainnet" }

[addresses]
libra2_framework = "0x1"
# replace the admin_addr with the actual admin address we created using CLI
admin_addr = "0xbeef"