[package]
name = "libra2-faucet-service"
description = "Libra2 Faucet Service"
version = "2.0.2"

# Workspace inherited keys
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
publish = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
anyhow = { workspace = true }
libra2-faucet-core = { workspace = true }
libra2-logger = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }
