name: "Release libra2-node"
on:
  workflow_dispatch:
    inputs:
      release_tag:
        type: string
        required: true
        description: "The release tag to create. E.g. `libra2-node-v0.2.3`:"
      branch:
        type: string
        required: true
        description: "The branch to cut the release from"
      release_title:
        type: string
        required: false
        description: 'Name of the release, e.g. "Aptos Node Release v1.2.3":'

jobs:
  release-libra2-node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - uses: actions/setup-python@v4

      - name: Bump libra2-node version
        uses: aptos-labs/aptos-core/.github/actions/release-libra2-node@main
        with:
          release_tag: ${{ inputs.release_tag }}
          libra2_node_cargo_toml: libra2-node/Cargo.toml

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@a4f52f8033a6168103c2538976c07b467e8163bc # pin@v6.0.1
        with:
          add-paths: libra2-node
          title: "[libra2-node] update release version"
          body: Automated release bump for ${{ inputs.release_tag }}. Change the PR base accordingly
          commit-message: "[libra2-node] update release version"
          branch: auto-release-${{ inputs.release_tag }}
          delete-branch: true
